name: Version & Publish

on:
  push:
    branches: [develop]
    paths:
      - 'packages/gx-breadcrumb/**'
      - 'packages/gx-card/**'
      - 'packages/gx-drag-drop/**'
      - 'packages/gx-styles/**'
      - 'packages/gx-ui/**'
      - '.github/workflows/release.yml'
      - '.changeset/**'
    
  workflow_dispatch:

concurrency:
  group: release-develop
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: yarn

      - run: corepack enable
      - run: yarn install --frozen-lockfile

      - name: Check publishable packages
        id: cs
        run: |
          set -e
          yarn changeset status > /tmp/cs.txt || true
          echo "==== changeset status ===="
          cat /tmp/cs.txt || true
          if grep -q "No unreleased changesets found" /tmp/cs.txt; then
            echo "publish=false" >> $GITHUB_OUTPUT
          else
            echo "publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Version packages
        if: steps.cs.outputs.publish == 'true'
        run: |
          yarn changeset version
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -am "chore: version packages [skip ci]"
            git push
          fi

      - name: Build
        if: steps.cs.outputs.publish == 'true'
        run: yarn build || echo "No build scripts"

      - name: Enable npm provenance
        if: steps.cs.outputs.publish == 'true'
        run: npm config set provenance true

      - name: Publish to npm
        if: steps.cs.outputs.publish == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn changeset publish --access public